### PR TITLE
Support updating of atomic host

### LINKED ISSUE #75: We should provide an option to update the machine
Some users might not have a completely up to date base box.
They might also want to ensure they have the latest packages if they are hacking on something that changes very often (eg: kubernetes).
Since we live in the dark ages of good internet, it might be nice to offer to update the vagrant box on first up, instead of requiring the user to do this manually, since it might be faster than re-downloading or building a new base image.

This should be a config option named 'update' or similar. It would be true/false, with a default to false.
It should only run on first up, and so should be in the "only one once" part of the Vagrantfile, eg: here:
https://github.com/purpleidea/oh-my-vagrant/blob/master/vagrant/Vagrantfile#L764 (i think).

It should run the yum update command with the shell provisioner...

Cheers,
James

PS: Bonus points for a future version of the patch:
Once we can detect atomic (not merged yet) then do an atomic update instead...

### PR DESCRIPTION
**Pull request by pschiffe**
Resolves #75

### CODE REVIEW

**Comment by purpleidea** [comment]
@pschiffe Thanks for the patch! Can you confirm that you've tested this?

**Comment by pschiffe** [comment]
@purpleidea Yes, I'm using it.

**Comment by purpleidea** [comment]
On Mon, Aug 24, 2015 at 7:42 AM, Peter Schiffer <notifications@github.com>
wrote:

> @purpleidea <https://github.com/purpleidea> Yes, I'm using it.



Okay great! Merged! Thanks

I think I was curious to know if a reboot would be necessary... SInce I
think it would, do we need a reboot option?
Let's think on this.

Cheers

**Comment by pschiffe** [comment]
Well, when doing `yum -y update` reboot is not always necessary, but when doing `atomic host upgrade`, manual reboot is always required. Having `reboot_after_provision` option in `omv.yaml` might be pretty convenient, yes.

**Comment by purpleidea** [comment]
On Mon, Aug 24, 2015 at 8:50 AM, Peter Schiffer <notifications@github.com>
wrote:

> Well, when doing yum -y update reboot is not always necessary, but when
> doing atomic host upgrade, manual reboot is always required. Having
> reboot_after_provision option in omv.yaml might be pretty convenient, yes.
>


Agreed, want to send a patch and/or open an issue? I think we should name
the flag "reboot", and it should naturally default to false.

Thanks!

**Comment by pschiffe** [comment]
OK, so I was looking into this and I didn't find a sane way how to do it in plain Vagrantfile. Reboot option will probably need vagrant plugin - I think this one should do it - https://github.com/aidanns/vagrant-reload
What do you think? Is it OK to depend on another vagrant plugin?

**Comment by purpleidea** [comment]
@pschiffe I don't think that plugin would be useful / necessary. I think a simple shell 'reboot' command would do it.

**Comment by pschiffe** [comment]
I tried that but without luck. With `vm.vm.provision 'shell', inline: 'reboot'` I get:
```
==> omv1: Running provisioner: shell...
SSH connection was refused! This usually happens if the VM failed to
boot properly. Some steps to try to fix this: First, try reloading your
VM with `vagrant reload`, since a simple restart sometimes fixes things.
If that doesn't work, destroy your VM and recreate it with a `vagrant destroy`
followed by a `vagrant up`. If that doesn't work, contact a Vagrant
maintainer (support channels listed on the website) for more assistance.
```

This is probably because SSH connection is closed during the VM reboot but Vagrant in this case automatically aborts provisioning and stops.

The plugin I mentioned reboots the VM, waits until it's back up and then returns control to Vagrant to continue provisioning.

**Comment by purpleidea** [comment]
@pschiffe If the reload thing does what we want, then let's do that I guess!
We probably want to make sure that it "runs once" in the runonce section of the code...

**Pull request merged**
