### PR TITLE
Added 'reboot' option

### PR DESCRIPTION
**Pull request by pschiffe**

### CODE REVIEW

**Comment by pschiffe** [comment]
What do you think?

**Comment by purpleidea** [comment]
@pschiffe Yowza!

I didn't test this yet, but after a quick read-through it looks pretty darn perfect.
So... THANK YOU!

I just need a quick ACK from you that you tested it, and it works as expected, and if so I'll merge :)

Cheers,
James

**Comment by pschiffe** [comment]
@purpleidea Hi James, yes, I tested it. It works as expected, reboots the guest only on the first run.

**Comment by purpleidea** [comment]
On Fri, Aug 28, 2015 at 12:48 PM, Peter Schiffer <notifications@github.com>
wrote:

> @purpleidea <https://github.com/purpleidea> Hi James, yes, I tested it.
> It works as expected, reboots the guest only on the first run.



Awesome! Merged :)

**Comment by purpleidea** [comment]
@pschiffe I've made a new release including this commit.

I've tagged it as v 1.0.1 and it should be available in copr shortly.

Cheers,
James

**Comment by pschiffe** [comment]
@purpleidea Thanks James!

**Comment by purpleidea** [comment]
On Fri, Aug 28, 2015 at 4:56 PM, Peter Schiffer <notifications@github.com>
wrote:

> @purpleidea <https://github.com/purpleidea> Thanks James!



No, thank you!

**Pull request merged**
