### PR TITLE
add extra disk options

### PR DESCRIPTION
**Pull request by rtweed**
Submitted as new PR.

### CODE REVIEW

**Comment by purpleidea** [comment]
@rtweed Patch looks pretty darn perfect... Two small things:

1) Why do you have the "if vm_disks.to_i !=0" condition? Isn't this automatically covered by the loop anyways? Your comment actually says it does ;)

2) your line ( 1..vm_disks) line has some extra whitespace (a tab) before the "1..", I guess just a typo that needs removing.

Please git commit --amend and push ... --force so we can merge this beauty :)

Thanks!

**Comment by purpleidea** [comment]
@rtweed Lastly, one small tiny issue failed my test case...

james@freed:~/code/oh-my-vagrant (feat/disks)$ git whitespace-check 
examples/ansible.yaml:8: trailing whitespace.
+:disksize: '40G' 

^^ That line has an extra space at the end :P

**Comment by purpleidea** [comment]
@rtweed Sorry, really last thing... I just noticed your patch used spaces to indent, whereas the whole code base uses tabs. Please fix that too!

Thanks again!

**Comment by rtweed** [comment]
OK, this one I can't fathom. They all show up as tabs in vim. :D

Rest will be amended/merged later this morning.

-Russell

**Comment by rtweed** [comment]
Fixed, commit amended. This a was a vim thing. :)

**Comment by purpleidea** [comment]
@rtweed This PR has about 8 merge commits... Please squash this all into one, and remove the whitespace found in

examples/ansible.yaml:8: trailing whitespace.
+:disksize: '40G'     <--- whitespace here...

**Comment by rtweed** [comment]
Can't do the squash; it fails every time, presumably as there's now a merge conflict someplace. 

I have, however, removed that trailing whitespace. :)

**Comment by purpleidea** [comment]
Hey @rtweed ! Thanks again for your patch. I hope you don't mind, but I squashed it for you, and added a small clean up as a subsequent patch on top of it.

Your code is now merged as: https://github.com/purpleidea/oh-my-vagrant/commit/ae484b2e5fad6f8188d861a97c64b874fe3965ab

Thanks again for your contributions!

**Pull request closed without merging**
