### PR TITLE
Add 'disks' and 'disksize' options

### PR DESCRIPTION
**Pull request by rtweed**
Add 'disks' and 'disksize' options to allow addition of extra volumes to libvirt instances.

### CODE REVIEW

**Comment by purpleidea** [comment]
Cool patch, thanks! Some review:

1) Please add the --omv-disks / omv-disksize args in the correct spots...
2) Similarly, if you could have the vm_disks and other args match the order in the omv that would be slightly cleaner (nitpick)
3) Similarly, please move the disks portion in the libvirt section to below the memory for consistency...
4) Why 20G? If there's a reason, I'm okay with it, otherwise perhaps use the vagrant default of 40G
5) The examples/ folder needs the disks entries added in each file
6) Please squash everything down into a single commit

Sorry for the number of comments. Your patch is quite good, it just needs some small tweaks!

**Comment by rtweed** [comment]
Resubmitted as PR #108. Much cleaner. :)

**Comment by purpleidea** [comment]
@rtweed Patch looks pretty darn perfect... Two small things:

1) Why do you have the "if vm_disks.to_i !=0" condition? Isn't this automatically covered by the loop anyways? Your comment actually says it does ;)

2) your line (        1..vm_disks) line has some extra whitespace (a tab) before the "1..", I guess just a typo that needs removing.

Please git commit --amend and push ... --force so we can merge this beauty :)

Thanks!

**Comment by purpleidea** [comment]
Woops. This comment ^^^ was meant for #108

**Comment by rtweed** [comment]
1) Call it an extra check. :) That comment was actually already there,
but the condition check wasn't.. it just bombed out with 'disks = 0'
previously.

2) Taken care of!

**Pull request closed without merging**
