### PR TITLE
updating Vagrantfile to support VM / box updates on vagrant up

### PR DESCRIPTION
**Pull request by scollier**
Hi @purpleidea.  Please check out this patch which allows a blind update of the vagrant box.  If you set "vm_update" to "true" in the omv yaml file, it will run a update on vagrant up.

### CODE REVIEW

**Comment by purpleidea** [comment]
Thanks @scollier !

Some review:

It should be called "update", globally... The vm_update variable should be used for the machine specific update values. Look at vm_puppet for example: https://github.com/purpleidea/oh-my-vagrant/blob/master/vagrant/Vagrantfile#L734

The update part is good, but I think it should be located here:
https://github.com/scollier/oh-my-vagrant/blob/796243a536e4f7df11f04cbea894e4dedd5eed05/vagrant/Vagrantfile#L904
After subscription manager, and in the "run once" section.

Thanks!

**Comment by purpleidea** [comment]
Your updates are perfect, but please make one small change please:

Over here... https://github.com/purpleidea/oh-my-vagrant/blob/master/vagrant/Vagrantfile#L739
You should probably have a vm_update variable... The vm_foo versions are the vm specific settings, where as the foo (by itself) versions are the globals that are used if no vm specific setting is made.
Once you change that, your "if update do yum..." line will have to be if vm_update ...

**Comment by purpleidea** [comment]
If you'd like a bonus challenge, detect if we're using atomic (look in the code for "atomic-" to know how) and if so run the atomic update command instead.

My understanding is that after the update, you need to reboot, so perhaps the update command should be something like:

atomic-update-command && echo shutting down for update to apply, something, something... && poweroff
?
The atomic-update-command should be something that updates atomic, but that returns true only if there were updates to do... Use whatever the correct shell foo is.

**Comment by scollier** [comment]
@purpleidea I changed the default to false.  Now it's probably not ready to merge at all.  I took a look at the vm_*  settings and basically copied other code you have there.  I'm honestly not sure if it's right at all.  I'm not sure how those are invoked since there's no modification of the omv.yaml file.  We should discuss.

**Comment by purpleidea** [comment]
Apart from the two comments, your patch is perfect. I'll ping you offline to discuss so you're comfortable with the code base.

When you amend your patch, please change the commit messages to something more sane :P

**Comment by purpleidea** [comment]
@scollier AWESOME!

LGTM

MERGED

SWEET

...
Merged in: https://github.com/purpleidea/oh-my-vagrant/commit/f776a697ccad9ec91f4463694150cace0434f18a

**Pull request closed without merging**
