### PR TITLE
Draft attempt in getting VirtualBox support

### PR DESCRIPTION
**Pull request by flavio-fernandes**
This is a dry-run attempt in getting virtual-box to work with oh-my-vagrant.
While it should not disturb libvirt users, this is likely incomplete due to the
missing mappings in vb for Vagrant.configure().

### CODE REVIEW

**Comment by purpleidea** [comment]
@flavio-fernandes Awesome work thanks...

Can you elaborate on what missing mappings there are?
Is this complete enough that it works, or still needs additions?

LMK, and we'll get this merged!
Cheers,
James

**Comment by flavio-fernandes** [comment]
I think is is benign to merge, but the missing mappings I'm referring to are here [1].
In a nutshell, we need to identify what the commented out lines do in libvirt and find
a corresponding setting in virtual-box; if possible.

[1]: https://github.com/flavio-fernandes/oh-my-vagrant/commit/bff01ff97cd499985a933e51a2a7b5e59e2597e2#diff-ca9fe86ed187adb25755f6a8be2b3154R984

**Comment by purpleidea** [comment]
@flavio-fernandes Two small issues above to fix.
Please _test_ and confirm it works. If it does, then squash these commits and I'll merge it :)

Thanks again!

**Comment by flavio-fernandes** [comment]
Moved to https://github.com/purpleidea/oh-my-vagrant/pull/74

**Pull request closed without merging**
