### PR TITLE
Give RHEL Server and Atomic Host a little bit more air to breath

### PR DESCRIPTION
**Pull request by goern**
straight forward, maybe we should refactor that out to a configurable per box?

### CODE REVIEW

**Comment by purpleidea** [comment]
Agreed all around...

So let's add this (with good reasoning), but have it be configurable, per machine.
The approach omv uses of having default globals, but also per machine overrides in the vms array will work well.

It should be straight forward if you're familiar with the code base. I'm happy to give pointers if whoever is working on this is stuck.

**Comment by purpleidea** [comment]
PS: @cgwalters Many thanks for popping in to help review. It's much appreciated!

**Comment by goern** [comment]
@purpleidea need pointer, you remember I screwed it up for you a few times...

**Comment by purpleidea** [comment]
@goern pointer to writing the patch?

This recent patch my @scollier is a good example of where in the code base to be: https://github.com/purpleidea/oh-my-vagrant/commit/f776a697ccad9ec91f4463694150cace0434f18a

The few modifications: you're looking at int's instead of bools, but that should be enough to get you going. If not, ping me offline and we can pair code on it.

**Comment by purpleidea** [comment]
@goern Are you planning on updating this patch, or should I close?

**Comment by purpleidea** [comment]
Also! @cgwalters had commented here, and now the comments are missing. What happened? Did GH loose data?

**Comment by purpleidea** [comment]
For the record, @cgwalters pointed out that they old messages are here: https://github.com/goern/oh-my-vagrant/commit/705af9e60c3bf9e27db2a2ede52ae472777b6893 and they dissapear when you rebase. This is lame @github !

**Pull request closed without merging**
