### PR TITLE
Documented :poolid: and :repos: omv.yaml options

### PR DESCRIPTION
**Pull request by br0ziliy**
Please see another piece of docs :)

### CODE REVIEW

**Comment by purpleidea** [comment]
@br0ziliy 
This is pretty awesome, thanks! Small review:

1) "choice" not "choise"
2) Is that particular poolid random or safe to include? If it's an actual poolid I think that leaks your subscription files, so best to ensure it's fake.

Please fix and rebase, thanks!

**Comment by br0ziliy** [comment]
@purpleidea I could use some guidance here I believe... How do I do this modification without creating another commit?..

**Comment by purpleidea** [comment]
@br0ziliy In your branch, make the changes you want. `git add -p` them or git add them how you usually do. THEN do git commit --amend instead of plain git --commit and it will merge this new commit into last commit. Then do git push whatever whatever --force to overrwrite this patch. Ping here when done because github doesn't notify on this change.

HTH

**Comment by br0ziliy** [comment]
@purpleidea Thanks for the tip James, this worked.

> 2) Is that particular poolid random or safe to include?

It's from the official Red Hat document linked in the [Red Hat Subscription Manager pool(s)](https://access.redhat.com/documentation/en-US/Red_Hat_Subscription_Management/1/html-single/RHSM/#subscr-about-pools) (section `⁠4.1.1. Pools and Available Subscriptions`), so I believe it's safe to include it.

**Comment by purpleidea** [comment]
Merged, thanks!

**Pull request merged**
