### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by br0ziliy**
So I had some spare cycles and added some documentation.
Please review and let me know if it's fine.

### CODE REVIEW

**Comment by purpleidea** [comment]
@br0ziliy Awesome!! This is great!!

I have a few small fixes if you're willing to patch them (rebased in ideally if you're comfortable doing so). If you prefer not to, then I can patch on top, it's minor stuff.

> VMs, which is not you want probably.
Missing a word, although you _might_ actually want this if you have a base cluster and N worker machines. So add the missing word, and change to "might not want" ? Make sense-- Example (although pseudo example because it's broken: https://github.com/purpleidea/oh-my-vagrant/blob/master/examples/puppet-gluster.yaml note the use of puppet, vms and count.

I think two? of the lines are unnecessarily wrapped at longer than 80. Could you wrap them? Leaving URL's as longer than 80 is fine.

> centos-7
There's no centos-7, there is centos-7.0 or 7.1

Altogether this is beautiful. I'm looking forward to merging this soon.

Thanks again,
James

**Comment by br0ziliy** [comment]
@purpleidea did that. Also changed wording in the `:count` note in `:vms` section, to be a bit more clear on the `:count` usage.

**Comment by purpleidea** [comment]
@br0ziliy This is great, thanks again. I didn't know why there was a merge commit on the end, so everything except for that last commit is now in git master.

Please check and if I missed anything, let me know! github is too stupid to tell that these commits are all merged, so I'll close manually.

AWESOME!
Cheers,
James

**Comment by br0ziliy** [comment]
@purpleidea Thanks James, we're all set.
Not sure about that merge commit as well, probably my Git skills suck or I don't know. Anyway - it's merged, this is what matters :) Thanks again!

**Comment by purpleidea** [comment]
On Sat, Aug 29, 2015 at 7:48 PM, br0ziliy <notifications@github.com> wrote:

> @purpleidea <https://github.com/purpleidea> Thanks James, we're all set.
> Not sure about that merge commit as well, probably my Git skills suck or I
> don't know. Anyway - it's merged, this is what matters :) Thanks again!



My pleasure!

**Pull request closed without merging**
