### PR TITLE
Adding Oh My Vagrant! logo

### PR DESCRIPTION
**Pull request by mairin**
This commit adds the Oh My Vagrant! logo to a new 'art' directory in the repo. The SVG is the Inkscape SVG source; the PNG is the logo file. The fonts used in the logo are Pacifico and Alfa Slab One; both are Open Font License fonts. I also added my name to AUTHORS and updated the README to include the logo in this PR.

### CODE REVIEW

**Comment by purpleidea** [comment]
@mairin Thank you so much for the beautiful logo and patch! Could you make two small changes please?
1) Authors name in alphabetical order?
2) Can you move the logo to below the top title line, and use the link of: https://raw.githubusercontent.com/purpleidea/oh-my-vagrant/master/art/omv.png so that it matches upstream?

Thanks again, so excited to get this commit in. Ps: hope it's okay, but you're mentioned here: https://ttboj.wordpress.com/2015/08/18/thanking-oh-my-vagrant-contributors-for-version-1-0-0/

**Comment by mairin** [comment]
I can't do this, sorry. I can't deal with git's stupidity.

**Comment by mairin** [comment]
Ugh, hold on, it seems like I was stuck in a stupid loop because I wasn't doing push --force when trying to fix the commits

**Comment by purpleidea** [comment]
@mairin No worries, I'll wait, and I'm more than happy to help you deal with git anytime. I owe you one! :)

**Comment by mairin** [comment]
Okay, I think that fixed it???

**Comment by purpleidea** [comment]
@mairin Actually this is perfect, and I like your patch, even what you did in the AUTHORS file :)
I just noticed that you used the old version of the logo without the capital M in My.
Do you want me to merge this as is, and should I patch the svg on top, or do you want to resubmit that part?

**Comment by mairin** [comment]
LOL after that epic git journey! ill fix it tomorrow now that i (sort of) know how to rebase... it's on my workstation and i'm home now.

**Comment by purpleidea** [comment]
On Tue, Sep 1, 2015 at 4:58 PM, Máirín Duffy <notifications@github.com>
wrote:

> LOL after that epic git journey! ill fix it tomorrow now that i (sort of)
> know how to rebase... it's on my workstation and i'm home now.
>

Sounds good! After this you'll be a git pro!

FWIW, in case it helps, the pattern I usually use is:

write the patch...
git add, git commit ...
# push to your branch, eg:
git push origin feat/logo

# oops, make a change...
git add ...
git commit --amend #does the rebase on the last commit automatically

git push origin feat/logo --force

Thanks again!

**Comment by mairin** [comment]
Yeh the problem is that this was done in two commits, so I had to go back two commits meaning i had to use rebase --interactive. But that wasn't the issue, the issue was that git wouldn't let me push the commit edits without a merge (since the remote was commits 'ahead' of my local) and the merge resulted in undoing the fixes i had just did - in a loop. The tutorial I was reading said to never use git push --force, but that was the only way to break out of the loop.

Anyway, should be fixed now?

**Comment by purpleidea** [comment]
@mairin Yuckness, well your patch _is_ really perfect, and it has been merged to master!! Thank you again!

PS: do you know which package (if any) those fonts are available in Fedora?

**Comment by mairin** [comment]
They aren't packaged, unfortunately. They should be on the google fonts directory tho, http://google.com/fonts

**Comment by purpleidea** [comment]
On Thu, Sep 3, 2015 at 2:04 PM, Máirín Duffy <notifications@github.com>
wrote:

> They aren't packaged, unfortunately. They should be on the google fonts
> directory tho, http://google.com/fonts
>


Awesome! Found and added:
https://github.com/purpleidea/oh-my-vagrant/commit/6cb874c24cd169f75fb453c7fc21c63f740d5f5b

Cheers!

**Pull request merged**
